// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/servicemanagement/v1/servicemanager.proto

package com.google.api.servicemanagement.v1;

public interface DisableServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.servicemanagement.v1.DisableServiceResponse)
    com.google.protobuf.MessageOrBuilder {
}
