// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/servicemanagement/v1/servicemanager.proto

package com.google.api.servicemanagement.v1;

public interface EnableServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.servicemanagement.v1.EnableServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. Name of the service to enable. Specifying an unknown service name will
   * cause the request to fail.
   * </pre>
   *
   * <code>string service_name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <pre>
   * Required. Name of the service to enable. Specifying an unknown service name will
   * cause the request to fail.
   * </pre>
   *
   * <code>string service_name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <pre>
   * Required. The identity of consumer resource which service enablement will be
   * applied to.
   * The Google Service Management implementation accepts the following
   * forms:
   * - "project:&lt;project_id&gt;"
   * Note: this is made compatible with
   * google.api.servicecontrol.v1.Operation.consumer_id.
   * </pre>
   *
   * <code>string consumer_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The consumerId.
   */
  java.lang.String getConsumerId();
  /**
   * <pre>
   * Required. The identity of consumer resource which service enablement will be
   * applied to.
   * The Google Service Management implementation accepts the following
   * forms:
   * - "project:&lt;project_id&gt;"
   * Note: this is made compatible with
   * google.api.servicecontrol.v1.Operation.consumer_id.
   * </pre>
   *
   * <code>string consumer_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for consumerId.
   */
  com.google.protobuf.ByteString
      getConsumerIdBytes();
}
